# log-file="C:/Users/Steve/AppData/Roaming/mpv/mpv.log"

sub-visibility=yes

# Preferred audio, subtitle languages
alang=jpn,jp
slang=jpn,jp

# Saves last position
save-position-on-quit=yes

# Load all subs containing the media filename.
sub-auto=fuzzy
# Load all audio files containing the media filename.
audio-file-auto=exact

# 
aid=1
sub-fix-timing=yes
autofit-larger=100%x100%
geometry=50%:50%

# sub-font="Noto Serif JP"
sub-font="Noto Sans SC Light"
sub-font-provider=fontconfig
sub-font-size=75
sub-pos=95
sub-scale-by-window=no
sub-ass-override=strip

# Uncomment this if you want mpv to override styles from SubStation Alpha (.ssa/.ass) subtitles
# sub-ass-override=force

# Improves audio when the playback speed is changed.
af-add=scaletempo2

# Screenshots
screenshot-directory="~/Pictures/Screenshots/"
screenshot-template="%F_%wHh%wMm%wSs%wTms"
screenshot-format=jpg
screenshot-jpeg-quality=90
screenshot-high-bit-depth=yes