# Minimal overrides from defaults.lua

deck_name=Bank::subs2srs
note_tag=subs2srs
disable_gui_browse=yes
menu_font_size=24
sentence_field=none
image_field=none
autoclip=yes
miscinfo_enable=no
secondary_sub_lang=eng,en
autoclip_custom_args=/usr/local/bin/goldendict %MPV_PRIMARY%
nuke_spaces=no
animated_snapshot_height=300
audio_bitrate=24k
use_ffmpeg=yes
#ffmpeg_audio_args=-af areverse,silenceremove=start_periods=1:start_threshold=-35dB:stop_periods=-1:stop_duration=0.3:stop_threshold=-35dB:stop_silence=0.08:start_silence=0.2,areverse
